### ISSUE TITLE
a-Tags Are rendered w/o href attribute

### ISSUE THREAD

**Issue by vanthome** [ember-vcl/navigation#1]
In previous versions I set this up such that the `href` attribute is populated with the actual link.
This is _essential__ for SEO reasons.
The solution inclue to use the new `vcl-link` component as it already cares about actions vs. browser native event handling.

**Comment by OrKoN** [comment]
I think a-tag are rendered with w/ href, if `href` is defined in the `items` list. For example, demo1 is missing hrefs https://github.com/ember-vcl/navigation/blob/master/demo/example1/application.js, while demo2 has them https://github.com/ember-vcl/navigation/blob/master/demo/example2/application.js I have checked that they show up in the online demo: http://ember-vcl.github.io/navigation/demo/example2.html

If we could generate the missing hrefs based on the `route` property, it would be great.
